### ISSUE TITLE
Expired refresh token

### ISSUE THREAD

**Issue by burtonmsp** [lwhitelock/MSP-Automation#3]
Our refresh token expired after 90 days, and we tried renewing it but it doesn't work.

New-PartnerAccessToken : AADSTS700082: The refresh token has expired due to inactivity.The token was issued on
2022-09-08T12:34:22.6440885Z and was inactive for 90.00:00:00.

How to renew? I can't see anything online to point us in the right direction

**Comment by lwhitelock** [comment]
You can use the script from step 6 here https://github.com/lwhitelock/HuduM365Automation/blob/master/Troubleshooting.md

**Comment by burtonmsp** [comment]
Thanks for the quick reply. I ran the script and it generates the tokens, however I now get a new error. It can read the tenant companies, but then shows this for each (not all tenants have conditional access yet but message is same for all):

New-PartnerAccessToken : AADSTS50020: User account '{EmailHidden}' from identity provider
'https://sts.windows.net/<applicationID>/' does not exist in tenant <tenant name> and cannot access the application '<applicationID>'(Partner Center Web App) in that tenant. The account needs to be added as an external user in the tenant 
first. Sign out and sign in again with a different Azure Active Directory user account.

I'm probably missing something silly but I can't see a proper answer online. Thanks
